In [1]:
import numpy as np
import pandas as pd

In [2]:
def print_puzzle(state):
  print(np.array(state).reshape(3,3))
  print()

# **BFS**

---

In [9]:
src = [1, 2, 3, 4, 5, 6, 0, 7, 8]
target = [1, 2, 3, 4, 5, 6, 7, 8, 0]

print("Initial state: ")
print_puzzle(src)       #initial state
print()

print("Goal state: ")
print_puzzle(target)    #goal state
print()

print("BFS solution:")
bfs(src, target)

Initial state: 
[[1 2 3]
 [4 5 6]
 [0 7 8]]


Goal state: 
[[1 2 3]
 [4 5 6]
 [7 8 0]]


BFS solution:
[[1 2 3]
 [4 5 6]
 [0 7 8]]

[[1 2 3]
 [0 5 6]
 [4 7 8]]

[[1 2 3]
 [4 5 6]
 [7 0 8]]

[[0 2 3]
 [1 5 6]
 [4 7 8]]

[[1 2 3]
 [5 0 6]
 [4 7 8]]

[[1 2 3]
 [4 0 6]
 [7 5 8]]

[[1 2 3]
 [4 5 6]
 [7 8 0]]

Goal Found


In [8]:
def bfs(src,goal):
  queue = [] #stores the nodes to be visited
  queue.append(src) #src is the first node to be visited
  visited = [] #nodes which are explored
  while len(queue) > 0:
    node = queue.pop(0)
    visited.append(node)
    print_puzzle(node)
    if node == goal:
      print("Goal Found")
      return

    poss_moves_to_do = possible_moves(node, visited)

    for move in poss_moves_to_do:
      if move not in visited and move not in queue:
        queue.append(move)



In [5]:
def possible_moves(node, visited):
  direction = []
  loc = node.index(0)

  if loc not in [0,1,2]:
    direction.append('u')

  if loc not in [6,7,8]:
    direction.append('d')

  if loc not in [0,3,6]:
    direction.append('l')

  if loc not in [2,5,8]:
    direction.append('r')

  possible_moves_it_can = []
  for i in direction:
    possible_moves_it_can.append(gen(node,loc,i))

  return [move for move in possible_moves_it_can if move not in visited]


In [7]:
def gen(state,loc, direction):
  temp = state.copy()
  if direction == 'u':
    temp[loc-3], temp[loc] = temp[loc], temp[loc-3]
  if direction == 'd':
    temp[loc+3], temp[loc] = temp[loc], temp[loc+3]
  if direction == 'r':
    temp[loc+1], temp[loc] = temp[loc], temp[loc+1]
  if direction == 'l':
    temp[loc-1], temp[loc] = temp[loc], temp[loc-1]

  return temp


# **DFS**

---



In [ ]:
import numpy as np

def dfs(src, target):
    stack = []          #nodes to be explored
    stack.append(src)

    exp = []            #explored nodes

    while len(stack) > 0:
        source = stack.pop()
        exp.append(source)

        print_puzzle(source)

        if source == target:
            print()
            print("Success! Goal state achieved!")
            return

        # If direction is possible then add state to move
        poss_moves_to_do = possible_moves(source, exp)

        for move in poss_moves_to_do:
            if move not in exp and move not in stack:
                stack.append(move)

In [ ]:
def possible_moves(state, visited_states):
    b = state.index(0)     #index of empty tile
    d = []                 #directions array

    if b not in [0, 1, 2]:                  # [0  1  2]
        d.append('u')                       # [3  4  5]
    if b not in [6, 7, 8]:                  # [6  7  8]
        d.append('d')
    if b not in [0, 3, 6]:
        d.append('l')
    if b not in [2, 5, 8]:
        d.append('r')

    pos_moves_it_can = []

    # For all possible directions, the state if that move is played
    for i in d:
        pos_moves_it_can.append(gen(state, i, b))

    return [move_it_can for move_it_can in pos_moves_it_can if move_it_can not in visited_states]

In [ ]:
def gen(state, m, b):
    temp = state.copy()

    if m == 'd':
        temp[b+3], temp[b] = temp[b], temp[b+3]

    if m == 'u':
        temp[b-3], temp[b] = temp[b], temp[b-3]

    if m == 'l':
        temp[b-1], temp[b] = temp[b], temp[b-1]

    if m == 'r':
        temp[b+1], temp[b] = temp[b], temp[b+1]

    return temp

In [ ]:
src = [1, 2, 3, 4, 5, 6, 0, 7, 8]     #initial state
target = [1, 2, 3, 4, 5, 6, 7, 8, 0]  #goal state

print("Initial state: ")
print_puzzle(src)       #initial state
print()

print("Goal state: ")
print_puzzle(target)    #goal state
print()

print("DFS solution:")
dfs(src, target)

Initial state: 
[[1 2 3]
 [4 5 6]
 [0 7 8]]


Goal state: 
[[1 2 3]
 [4 5 6]
 [7 8 0]]


DFS solution:
[[1 2 3]
 [4 5 6]
 [0 7 8]]

[[1 2 3]
 [4 5 6]
 [7 0 8]]

[[1 2 3]
 [4 5 6]
 [7 8 0]]


Success! Goal state achieved!
